blueprint:
  name: Smart Humidity Control (v1.2)
  description: >
    Automatically control humidity in your home based on house mean humidity.
    Includes special handling for bathroom and 4th floor humidity spikes with configurable offsets.
  domain: automation
  source_url: https://github.com/danielcherubini/Home-Assistant-Blueprints/blob/main/smart_humidity_control.yaml
  
  input:
    # Required entities
    house_humidity_sensor:
      name: House Humidity Sensor
      description: Sensor that measures the average humidity in your house
      selector:
        entity:
          filter:
            - domain: sensor
              device_class: humidity
    
    bathroom_humidity_sensor:
      name: Bathroom Humidity Sensor
      description: Sensor that measures humidity in the bathroom
      selector:
        entity:
          filter:
            - domain: sensor
              device_class: humidity
    
    fourth_floor_humidity_sensor:
      name: 4th Floor Humidity Sensor
      description: Sensor that measures humidity on the 4th floor
      selector:
        entity:
          filter:
            - domain: sensor
              device_class: humidity
    
    humidity_control_switch:
      name: Humidity Control Switch
      description: Switch that controls your dehumidification system (fan, AC, etc.)
      selector:
        entity:
          filter:
            - domain: switch

    mode_tracker:
      name: Mode Tracker Helper
      description: Input text helper to track which mode triggered the system (create one in Settings > Devices & Services > Helpers)
      selector:
        entity:
          filter:
            - domain: input_text

    # Optional notification
    notification_device:
      name: Notification Device (Optional)
      description: Mobile device to receive notifications when system turns on/off
      default: ""
      selector:
        device:
          filter:
            - integration: mobile_app

    dashboard_url:
      name: Dashboard URL (Optional)
      description: URL path to navigate to when notification is clicked (e.g., /lovelace/humidity)
      default: ""
      selector:
        text:
    
    # Thresholds

    house_humidity_max:
      name: House Humidity Maximum
      description: Turn on dehumidification when house humidity reaches this level (%)
      default: 65
      selector:
        number:
          min: 50
          max: 80
          step: 1
          unit_of_measurement: "%"
    
    house_humidity_min:
      name: House Humidity Minimum
      description: Turn off dehumidification when house humidity drops to this level (%)
      default: 55
      selector:
        number:
          min: 40
          max: 70
          step: 1
          unit_of_measurement: "%"
    
    bathroom_humidity_offset:
      name: Bathroom Humidity Offset
      description: Activate when bathroom humidity exceeds house mean by this amount (%)
      default: 10
      selector:
        number:
          min: 5
          max: 30
          step: 1
          unit_of_measurement: "%"

    bathroom_minimum_offset:
      name: Bathroom Minimum Offset
      description: Minimum offset from house mean to activate bathroom priority (%)
      default: 0
      selector:
        number:
          min: 0
          max: 15
          step: 1
          unit_of_measurement: "%"
    
    fourth_floor_humidity_offset:
      name: 4th Floor Humidity Offset
      description: Activate when 4th floor humidity exceeds house mean by this amount (%)
      default: 10
      selector:
        number:
          min: 5
          max: 30
          step: 1
          unit_of_measurement: "%"

    fourth_floor_minimum_offset:
      name: 4th Floor Minimum Offset
      description: Minimum offset from house mean to activate 4th floor priority (%)
      default: 0
      selector:
        number:
          min: 0
          max: 15
          step: 1
          unit_of_measurement: "%"

variables:
  house_humidity_sensor: !input house_humidity_sensor
  bathroom_humidity_sensor: !input bathroom_humidity_sensor
  fourth_floor_humidity_sensor: !input fourth_floor_humidity_sensor
  house_humidity_max: !input house_humidity_max
  house_humidity_min: !input house_humidity_min
  bathroom_humidity_offset: !input bathroom_humidity_offset
  bathroom_minimum_offset: !input bathroom_minimum_offset
  fourth_floor_humidity_offset: !input fourth_floor_humidity_offset
  fourth_floor_minimum_offset: !input fourth_floor_minimum_offset
  mode_tracker: !input mode_tracker
  notification_device_id: !input notification_device
  dashboard_url: !input dashboard_url
  house_humidity: "{{ states(house_humidity_sensor) | int(0) }}"
  bathroom_humidity: "{{ states(bathroom_humidity_sensor) | float(0) }}"
  fourth_floor_humidity: "{{ states(fourth_floor_humidity_sensor) | float(0) }}"
  bathroom_threshold: "{{ house_humidity + bathroom_humidity_offset }}"
  bathroom_minimum_threshold: "{{ house_humidity + bathroom_minimum_offset }}"
  fourth_floor_threshold: "{{ house_humidity + fourth_floor_humidity_offset }}"
  fourth_floor_minimum_threshold: "{{ house_humidity + fourth_floor_minimum_offset }}"
  current_mode: "{{ states(mode_tracker) }}"

trigger:
  - platform: state
    entity_id: !input house_humidity_sensor
    id: humidity_change

condition: []

action:
  - choose:
      # Bathroom priority mode - turn on when exceeds threshold, off when reaches house mean
      - conditions:
          - condition: trigger
            id: humidity_change
          - condition: template
            value_template: "{{ bathroom_humidity >= bathroom_threshold and bathroom_humidity >= bathroom_minimum_threshold }}"
          - condition: state
            entity_id: !input humidity_control_switch
            state: 'off'
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input humidity_control_switch
          - service: input_text.set_value
            target:
              entity_id: !input mode_tracker
            data:
              value: "bathroom"
          - if:
              - condition: template
                value_template: "{{ notification_device_id != '' }}"
            then:
              - service: notify.mobile_app_{{ device_attr(notification_device_id, 'name') | lower | replace(' ', '_') | replace('-', '_') }}
                data:
                  message: "Humidity Control - On (Bathroom: {{ bathroom_humidity }}% vs house mean {{ house_humidity }}%)"
                  title: "Smart Humidity"
                  data:
                    clickAction: "{{ dashboard_url if dashboard_url != '' else '/lovelace' }}"

      # Bathroom priority mode - turn off when reaches house mean
      - conditions:
          - condition: trigger
            id: humidity_change
          - condition: template
            value_template: "{{ bathroom_humidity <= house_humidity }}"
          - condition: state
            entity_id: !input humidity_control_switch
            state: 'on'
          - condition: template
            value_template: "{{ current_mode == 'bathroom' }}"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input humidity_control_switch
          - service: input_text.set_value
            target:
              entity_id: !input mode_tracker
            data:
              value: "idle"
          - if:
              - condition: template
                value_template: "{{ notification_device_id != '' }}"
            then:
              - service: notify.mobile_app_{{ device_attr(notification_device_id, 'name') | lower | replace(' ', '_') | replace('-', '_') }}
                data:
                  message: "Humidity Control - Off (Bathroom reached house mean: {{ bathroom_humidity }}%)"
                  title: "Smart Humidity"
                  data:
                    clickAction: "{{ dashboard_url if dashboard_url != '' else '/lovelace' }}"

      # 4th Floor priority mode - turn on when exceeds threshold, off when reaches house mean
      - conditions:
          - condition: trigger
            id: humidity_change
          - condition: template
            value_template: "{{ fourth_floor_humidity >= fourth_floor_threshold and fourth_floor_humidity >= fourth_floor_minimum_threshold }}"
          - condition: state
            entity_id: !input humidity_control_switch
            state: 'off'
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input humidity_control_switch
          - service: input_text.set_value
            target:
              entity_id: !input mode_tracker
            data:
              value: "fourth_floor"
          - if:
              - condition: template
                value_template: "{{ notification_device_id != '' }}"
            then:
              - service: notify.mobile_app_{{ device_attr(notification_device_id, 'name') | lower | replace(' ', '_') | replace('-', '_') }}
                data:
                  message: "Humidity Control - On (4th Floor: {{ fourth_floor_humidity }}% vs house mean {{ house_humidity }}%)"
                  title: "Smart Humidity"
                  data:
                    clickAction: "{{ dashboard_url if dashboard_url != '' else '/lovelace' }}"

      # 4th Floor priority mode - turn off when reaches house mean
      - conditions:
          - condition: trigger
            id: humidity_change
          - condition: template
            value_template: "{{ fourth_floor_humidity <= house_humidity }}"
          - condition: state
            entity_id: !input humidity_control_switch
            state: 'on'
          - condition: template
            value_template: "{{ current_mode == 'fourth_floor' }}"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input humidity_control_switch
          - service: input_text.set_value
            target:
              entity_id: !input mode_tracker
            data:
              value: "idle"
          - if:
              - condition: template
                value_template: "{{ notification_device_id != '' }}"
            then:
              - service: notify.mobile_app_{{ device_attr(notification_device_id, 'name') | lower | replace(' ', '_') | replace('-', '_') }}
                data:
                  message: "Humidity Control - Off (4th Floor reached house mean: {{ fourth_floor_humidity }}%)"
                  title: "Smart Humidity"
                  data:
                    clickAction: "{{ dashboard_url if dashboard_url != '' else '/lovelace' }}"

      # General humidity control
      - conditions:
          - condition: trigger
            id: humidity_change
        sequence:
          - choose:
              # Turn on dehumidification
              - conditions:
                  - condition: template
                    value_template: "{{ house_humidity >= house_humidity_max }}"
                  - condition: state
                    entity_id: !input humidity_control_switch
                    state: 'off'
                  - condition: template
                    value_template: "{{ current_mode == 'idle' }}"
                sequence:
                  - service: switch.turn_on
                    target:
                      entity_id: !input humidity_control_switch
                  - service: input_text.set_value
                    target:
                      entity_id: !input mode_tracker
                    data:
                      value: "general"
                  - if:
                      - condition: template
                        value_template: "{{ notification_device_id != '' }}"
                    then:
                      - service: notify.mobile_app_{{ device_attr(notification_device_id, 'name') | lower | replace(' ', '_') | replace('-', '_') }}
                        data:
                          message: "Humidity Control - On (House: {{ house_humidity }}%)"
                          title: "Smart Humidity"
                          data:
                            clickAction: "{{ dashboard_url if dashboard_url != '' else '/lovelace' }}"

              # Turn off dehumidification - only if not in priority mode
              - conditions:
                  - condition: template
                    value_template: "{{ house_humidity <= house_humidity_min }}"
                  - condition: state
                    entity_id: !input humidity_control_switch
                    state: 'on'
                  - condition: template
                    value_template: "{{ current_mode in ['general', 'idle'] }}"
                sequence:
                  - service: switch.turn_off
                    target:
                      entity_id: !input humidity_control_switch
                  - service: input_text.set_value
                    target:
                      entity_id: !input mode_tracker
                    data:
                      value: "idle"
                  - if:
                      - condition: template
                        value_template: "{{ notification_device_id != '' }}"
                    then:
                      - service: notify.mobile_app_{{ device_attr(notification_device_id, 'name') | lower | replace(' ', '_') | replace('-', '_') }}
                        data:
                          message: "Humidity Control - Off (House: {{ house_humidity }}%)"
                          title: "Smart Humidity"
                          data:
                            clickAction: "{{ dashboard_url if dashboard_url != '' else '/lovelace' }}"

mode: restart